-- 蒙西新能源交易系统 Supabase schema
-- 在 Supabase SQL Editor 中执行一次。

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  name text unique not null,
  short_name text,
  station_type text default '光伏',
  capacity_mw double precision default 0,
  active boolean default true,
  risk_upper double precision default 1.10,
  target_lower double precision default 0.80,
  trade_limit_mwh double precision default 100,
  min_spread double precision default 10,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.daily_summary (
  id bigint generated by default as identity primary key,
  station_id bigint not null references public.stations(id) on delete cascade,
  trade_date date not null,
  source_file text,
  file_hash text,
  lt_energy double precision default 0,
  lt_price double precision default 0,
  actual_energy double precision default 0,
  spot_price double precision default 0,
  unified_price double precision default 0,
  spot_fee double precision default 0,
  lt_diff_fee double precision default 0,
  energy_total double precision default 0,
  congestion double precision default 0,
  assessment double precision default 0,
  green_fee double precision default 0,
  regular_fee double precision default 0,
  mechanism_fee double precision default 0,
  risk_prevention double precision default 0,
  unit_fee double precision default 0,
  final_revenue double precision default 0,
  final_price double precision default 0,
  uploaded_at timestamptz default now(),
  unique(station_id, trade_date)
);

create table if not exists public.hourly_detail (
  id bigint generated by default as identity primary key,
  station_id bigint not null references public.stations(id) on delete cascade,
  trade_date date not null,
  hour_no integer not null check (hour_no between 1 and 24),
  lt_energy double precision,
  lt_price double precision,
  actual_energy double precision,
  spot_price double precision,
  unified_price double precision,
  spot_fee double precision,
  lt_diff_fee double precision,
  energy_total double precision,
  unique(station_id, trade_date, hour_no)
);

create index if not exists idx_daily_station_date on public.daily_summary(station_id, trade_date);
create index if not exists idx_hourly_station_date on public.hourly_detail(station_id, trade_date);

-- 当前 V1 使用 publishable key。开启 RLS，并给 anon/authenticated 最小 CRUD 权限。
alter table public.stations enable row level security;
alter table public.daily_summary enable row level security;
alter table public.hourly_detail enable row level security;

drop policy if exists "v1 stations access" on public.stations;
create policy "v1 stations access" on public.stations for all to anon, authenticated using (true) with check (true);
drop policy if exists "v1 daily access" on public.daily_summary;
create policy "v1 daily access" on public.daily_summary for all to anon, authenticated using (true) with check (true);
drop policy if exists "v1 hourly access" on public.hourly_detail;
create policy "v1 hourly access" on public.hourly_detail for all to anon, authenticated using (true) with check (true);

-- 注意：以上策略适合当前个人 V1 快速接入；正式公网部署前应接 Supabase Auth，
-- 再把策略收紧到 authenticated 用户/指定 user_id。